spring.application.name=tms-service
server.port=8083

spring.datasource.url=jdbc:postgresql://ep-withered-voice-adeh05dh-pooler.c-2.us-east-1.aws.neon.tech/task-service-db?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_ldDN8gsV3aBv
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true